name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
  schedule:
    # additionally run once per week (At 00:00 on Sunday) to maintain cache
    - cron: '0 0 * * 0'

jobs:
  windows-build:
    name: windows-build
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2.3
      name: Setup Haskell Stack
      with:
        ghc-version: "9.0.2"
        stack-version: "2.7.5"

    - name: Install Haskell dependencies
      run: |
        stack build --system-ghc --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc
